#pragma once

// #include "sub_app_config.h"

#undef NRF_LOG_BACKEND_RTT_ENABLED
#define NRF_LOG_BACKEND_RTT_ENABLED 1
#define NRF_LOG_BACKEND_UART_ENABLED 0
#define NRFX_UART_ENABLED 1
#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1
#define UART_ENABLED 1

#define UART_LEGACY_SUPPORT 0
#define NRF_LOG_BACKEND_UART_TX_PIN    20   // 根据实际TX引脚修改
#define NRF_LOG_BACKEND_UART_RX_PIN    17   // 通常可不接

#define UART0_ENABLED 1
#define NRFX_UART0_ENABLED 0

#undef NRF_LOG_ENABLED
#define NRF_LOG_ENABLED 0

#define NRF_LOG_BACKEND_UART_TEMP_BUFFER_SIZE 256

// 波特率（115200）
#define NRF_LOG_BACKEND_UART_BAUDRATE 30801920


#define NRF_LOG_USES_COLORS 0
#define NRF_LOG_COLOR_DEFAULT 0
#define NRF_LOG_ERROR_COLOR 0
#define NRF_LOG_WARNING_COLOR 0
#define NRF_LOG_BUFSIZE 1024
// #undef NRF_LOG_INFO_COLOR
// #define NRF_LOG_INFO_COLOR 0

#define APP_FIFO_ENABLED 1
#define APP_UART_ENABLED 1
#define APP_UART_DRIVER_INSTANCE 0

#define RTC2_ENABLED 2

#define TWI_ENABLED 1

#define NRFX_TWIM_ENABLED 1
#define TWI0_ENABLED 1
#define NRFX_TWI_ENABLED 1
// #define NRFX_TWIS_ENABLED 1